version: '3.8'
services:
  # gunicorn_web:
  #   container_name: django_project
  #   build:
  #     context: . # local base image dir
  #     ssh: ["default"] # mount the deafult ssh agent
  #     dockerfile: Dockerfile
  #     shm_size: '1gb'
  #     # platforms: ["linux/arm64","linux/arm32",]
  #     # cache_to:
  #     #   - type=local, dest=./deployment
  #   command: celery worker --app=blog --loglevel=info
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env
  #   environment:
  #     - DEBUG=True
  #     - DJANGO_SETTINGS_MODULE=core.settings
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   volumes:
  #     - ./docker/backup:/app
  #   networks:
  #     - main
  #   depends_on:
  #     - database
  #   labels:
  #     - com.digibrands.by=Chriford


  redis:
    container_name: redis
    image: redis:alpine
    labels:
      - com.digibrands.by=Chriford

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - static:/static
  #   ports:
  #     - "5354:5354"
  #   depends_on:
  #     - gunicorn_web
  #   labels:
  #     - com.digibrands.by=label
  elasticsearch:
    container_name: esearch
    image: elasticsearch:7.14.2
    ports: 
      - "9200:9200"
    environment:
      - discovery.type=single-node

  database:
    container_name: postgres_db
    image: postgres
    environment:
      POSTRES_DB: blog
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: digi.Brands7.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      - com.digibrands.by=Chriford

networks:
  main:

volumes:
  static:
  pgdata:
