version: '3.8'
services:
  gunicorn_web:
    build:
      context: . # use base image in the current dir and not on github
      ssh: ["default"] # mount the deafult ssh agent
      dockerfile: Dockerfile
      shm_size: '1gb'
      platforms: ["linux/arm64","linux/arm32",]
      # cache_to:
      #   - type=local, dest=./deployment    
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DEBUG=True
    volumes:
      - ./docker/backup:/app
    networks:
      - main
    depends_on:
      - database
    labels:
      - com.digibrands.by=Chriford=label


  redis:
    container_name: redis
    image: redis:alpine
    labels:
      - com.digibrands.by=Chriford=label

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/static
    ports:
      - 5354:80
    depends_on:
      - gunicorn_web
    labels:
      - com.digibrands.by=label

  database:
    container_name: postgres_db
    image: postgres
    environment:
      POSTRES_DB: blog
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: digi.Brands7.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      - com.digibrands.by=Chriford=label

networks:
  main:

volumes:
  static:
  pgdata:
